{
 "openapi": "3.0.1",
 "info": {
  "title": "new input value",
  "description": "overview.introduction",
  "termsOfService": null,
  "contact": null,
  "license": null,
  "version": "v3",
  "extensions": {
   "x-hubspot-api-use-case": "new use case"
  }
 },
 "servers": [
  {
   "url": "https://api.hubapiqa.com",
   "description": null,
   "variables": null,
   "extensions": null
  }
 ],
 "security": null,
 "tags": [
  {
   "name": "Batch",
   "description": null,
   "extensions": null
  }
 ],
 "paths": {
  "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Batch"
    ],
    "summary": "Read a batch of associations",
    "description": "Get the IDs of all `{toObjectType}` objects associated with those specified in the request body.",
    "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read",
    "deprecated": null,
    "security": [
     {
      "oauth2": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.read"
      ]
     },
     {
      "private_apps_legacy": [
       "contacts"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.write"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "oauth2_legacy": [
       "tickets"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "oauth2_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps_legacy": [
       "tickets"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Batch"
    ],
    "summary": "Create a batch of associations",
    "description": "Associate all pairs of objects identified in the request body.",
    "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create",
    "deprecated": null,
    "security": [
     {
      "oauth2": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.read"
      ]
     },
     {
      "private_apps_legacy": [
       "contacts"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.write"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "oauth2_legacy": [
       "tickets"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "oauth2_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps_legacy": [
       "tickets"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Batch"
    ],
    "summary": "Archive a batch of associations",
    "description": "Remove the associations between all pairs of objects identified in the request body.",
    "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive",
    "deprecated": null,
    "security": [
     {
      "oauth2": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.read"
      ]
     },
     {
      "private_apps_legacy": [
       "contacts"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.deals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "private_apps": [
       "crm.objects.companies.write"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.goals.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.companies.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.write"
      ]
     },
     {
      "oauth2_legacy": [
       "tickets"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.contacts.write"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.custom.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.line_items.write"
      ]
     },
     {
      "oauth2_legacy": [
       "e-commerce"
      ]
     },
     {
      "private_apps_legacy": [
       "tickets"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.goals.read"
      ]
     },
     {
      "oauth2": [
       "crm.objects.quotes.read"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.custom.write"
      ]
     },
     {
      "private_apps": [
       "crm.objects.quotes.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2_legacy": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "crm.objects.goals.write": "Write goals",
       "e-commerce": "e-commerce",
       "crm.objects.custom.write": "Change custom object records",
       "crm.objects.custom.read": "View custom object records",
       "crm.objects.goals.read": "Read goals",
       "tickets": "Read and write tickets"
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "oauth2": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "crm.objects.deals.write": " ",
       "crm.objects.quotes.read": "Quotes",
       "crm.objects.line_items.write": "Line Items",
       "crm.objects.companies.read": " ",
       "crm.objects.companies.write": " ",
       "crm.objects.contacts.write": " ",
       "crm.objects.contacts.read": " ",
       "crm.objects.quotes.write": "Quotes",
       "crm.objects.deals.read": " ",
       "crm.objects.line_items.read": "Line Items"
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps_legacy": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app-legacy",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   }
  },
  "extensions": {}
 },
 "extensions": null
}