{
 "openapi": "3.0.1",
 "info": {
  "title": "Marketing Events Extension",
  "description": "These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to:\n* Create, Read or update Marketing Event information in HubSpot\n* Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event.\n* Specify a URL that can be called to get the details of a Marketing Event.\n",
  "termsOfService": null,
  "contact": null,
  "license": null,
  "version": "v3",
  "extensions": null
 },
 "servers": [
  {
   "url": "https://api.hubapiqa.com",
   "description": null,
   "variables": null,
   "extensions": null
  }
 ],
 "security": null,
 "tags": [
  {
   "name": "Batch",
   "description": null,
   "extensions": null
  },
  {
   "name": "Attendance Subscriber State Changes",
   "description": null,
   "extensions": null
  },
  {
   "name": "Subscriber State Changes",
   "description": null,
   "extensions": null
  },
  {
   "name": "Marketing_Events_External",
   "description": null,
   "extensions": null
  },
  {
   "name": "Basic",
   "description": null,
   "extensions": null
  },
  {
   "name": "Settings",
   "description": null,
   "extensions": null
  },
  {
   "name": "Search",
   "description": null,
   "extensions": null
  }
 ],
 "paths": {
  "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Attendance Subscriber State Changes"
    ],
    "summary": "Record",
    "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids.",
    "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Subscriber State Changes"
    ],
    "summary": "Record",
    "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids. Note that the contact must already exist in HubSpot; a contact will not be create.",
    "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/delete": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Batch"
    ],
    "summary": "Delete multiple marketing events",
    "description": "Bulk delete a number of marketing events in HubSpot",
    "operationId": "post-/marketing/v3/marketing-events/events/delete",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/{externalEventId}/cancel": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Basic"
    ],
    "summary": "Mark a marketing event as cancelled",
    "description": "Mark a marketing event as cancelled.",
    "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/{externalEventId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Basic"
    ],
    "summary": "Get a marketing event",
    "description": "Returns the details of the Marketing Event with the specified id, if one exists.",
    "operationId": "get-/marketing/v3/marketing-events/events/{externalEventId}",
    "deprecated": null,
    "security": [
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": {
    "tags": [
     "Basic"
    ],
    "summary": "Create or update a marketing event",
    "description": "Upsets a Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.",
    "operationId": "put-/marketing/v3/marketing-events/events/{externalEventId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": {
    "tags": [
     "Basic"
    ],
    "summary": "Delete a marketing event",
    "description": "Deletes an existing Marketing Event with the specified id, if one exists.",
    "operationId": "delete-/marketing/v3/marketing-events/events/{externalEventId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Basic"
    ],
    "summary": "Update a marketing event",
    "description": "Updates an existing Marketing Event with the specified id, if one exists.",
    "operationId": "patch-/marketing/v3/marketing-events/events/{externalEventId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/upsert": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Batch"
    ],
    "summary": "Create or update multiple marketing events",
    "description": "Upset multiple Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.",
    "operationId": "post-/marketing/v3/marketing-events/events/upsert",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Subscriber State Changes"
    ],
    "summary": "Record",
    "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created.",
    "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Attendance Subscriber State Changes"
    ],
    "summary": "Record",
    "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses. If contact is not present it will be automatically created.",
    "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/{externalEventId}/complete": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Marketing_Events_External"
    ],
    "summary": null,
    "description": null,
    "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/complete",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Basic"
    ],
    "summary": "Create a marketing event",
    "description": "Creates a new marketing event in HubSpot",
    "operationId": "post-/marketing/v3/marketing-events/events",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.write"
      ]
     },
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/{appId}/settings": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Settings"
    ],
    "summary": "Retrieve the application settings",
    "description": "Retrieve the current settings for the application.",
    "operationId": "get-/marketing/v3/marketing-events/{appId}/settings",
    "deprecated": null,
    "security": [
     {
      "developer_hapikey": []
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Settings"
    ],
    "summary": "Update the application settings",
    "description": "Create or update the current settings for the application.",
    "operationId": "post-/marketing/v3/marketing-events/{appId}/settings",
    "deprecated": null,
    "security": [
     {
      "developer_hapikey": []
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/marketing/v3/marketing-events/events/search": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search for marketing events",
    "description": "Search for marketing events that have an event id that starts with the query string",
    "operationId": "get-/marketing/v3/marketing-events/events/search",
    "deprecated": null,
    "security": [
     {
      "oauth2_legacy": [
       "crm.objects.marketing_events.read"
      ]
     },
     {
      "private_apps_legacy": [
       "crm.objects.marketing_events.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2_legacy": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "crm.objects.marketing_events.write": "Write marketing events",
       "crm.objects.marketing_events.read": "Read marketing events"
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "developer_hapikey": {
    "type": "APIKEY",
    "description": null,
    "name": "hapikey",
    "$ref": null,
    "in": "QUERY",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps_legacy": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app-legacy",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   }
  },
  "extensions": {}
 },
 "extensions": null
}