{
 "openapi": "3.0.1",
 "info": {
  "title": "Landing Page and Site Page endpoints",
  "description": "Use these endpoints for interacting with Landing Pages and Site Pages",
  "termsOfService": null,
  "contact": null,
  "license": null,
  "version": "v3",
  "extensions": null
 },
 "servers": [
  {
   "url": "https://api.hubapiqa.com",
   "description": null,
   "variables": null,
   "extensions": null
  }
 ],
 "security": null,
 "tags": [
  {
   "name": "Site Pages",
   "description": null,
   "extensions": null
  },
  {
   "name": "Landing Pages",
   "description": null,
   "extensions": null
  }
 ],
 "paths": {
  "/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Retrieves a previous version of a Site Page",
    "description": "Retrieves a previous version of a Site Page",
    "operationId": "get-/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/revisions": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieves all the previous versions of a Landing Page",
    "description": "Retrieves all the previous versions of a Landing Page.",
    "operationId": "get-/cms/v3/pages/landing-pages/{objectId}/revisions",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/batch/update": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Update a batch of Site Pages",
    "description": "Update the Site Page objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/site-pages/batch/update",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/{objectId}/revisions": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieves all the previous versions of a Folder",
    "description": "Retrieves all the previous versions of a Folder.",
    "operationId": "get-/cms/v3/pages/landing-pages/folders/{objectId}/revisions",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}/restore": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Restore a previous version of a Site Page",
    "description": "Takes a specified version of a Site Page and restores it.",
    "operationId": "post-/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}/restore",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/schedule": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Schedule a Site Page to be Published",
    "description": "Schedule a Site Page to be Published",
    "operationId": "post-/cms/v3/pages/site-pages/schedule",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/multi-language/attach-to-lang-group": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Attach a site page to a multi-language group",
    "description": "Attach a site page to a multi-language group.",
    "operationId": "post-/cms/v3/pages/site-pages/multi-language/attach-to-lang-group",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Get all Landing Page Folders",
    "description": "Get the list of Landing Page Folders. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
    "operationId": "get-/cms/v3/pages/landing-pages/folders",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Create a new Folder",
    "description": "Create a new Folder",
    "operationId": "post-/cms/v3/pages/landing-pages/folders",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/multi-language/detach-from-lang-group": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Detach a site page from a multi-language group",
    "description": "Detach a site page from a multi-language group.",
    "operationId": "post-/cms/v3/pages/site-pages/multi-language/detach-from-lang-group",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/batch/create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Create a batch of Folders",
    "description": "Create the Folder objects detailed in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/folders/batch/create",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/revisions": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Retrieves all the previous versions of a Site Page",
    "description": "Retrieves all the previous versions of a Site Page.",
    "operationId": "get-/cms/v3/pages/site-pages/{objectId}/revisions",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/draft": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieve the full draft version of the Landing Page",
    "description": "Retrieve the full draft version of the Landing Page.",
    "operationId": "get-/cms/v3/pages/landing-pages/{objectId}/draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update a Landing Page draft",
    "description": "Sparse updates the draft version of a single Landing Page object identified by the id in the path.\nYou only need to specify the column values that you are modifying.\n",
    "operationId": "patch-/cms/v3/pages/landing-pages/{objectId}/draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Get all Landing Pages",
    "description": "Get the list of landing pages. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
    "operationId": "get-/cms/v3/pages/landing-pages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "new summary",
    "description": "Create a new Landing Page",
    "operationId": "post-/cms/v3/pages/landing-pages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}/restore-to-draft": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Restore a previous version of a Site Page, to the draft version of the Site Page",
    "description": "Takes a specified version of a Site Page, sets it as the new draft version of the Site Page.",
    "operationId": "post-/cms/v3/pages/site-pages/{objectId}/revisions/{revisionId}/restore-to-draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/ab-test/end": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "End an active A/B test",
    "description": "End an active A/B test and designate a winner.",
    "operationId": "post-/cms/v3/pages/site-pages/ab-test/end",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/batch/create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Create a batch of Landing Pages",
    "description": "Create the Landing Page objects detailed in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/batch/create",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/batch/update": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update a batch of Landing Pages",
    "description": "Update the Landing Page objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/batch/update",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/batch/read": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieve a batch of Landing Pages",
    "description": "Retrieve the Landing Page objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/batch/read",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/clone": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Clone a Landing Page",
    "description": "Clone a Landing Page",
    "operationId": "post-/cms/v3/pages/landing-pages/clone",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/{objectId}/revisions/{revisionId}/restore": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Restore a previous version of a Folder",
    "description": "Takes a specified version of a Folder and restores it.",
    "operationId": "post-/cms/v3/pages/landing-pages/folders/{objectId}/revisions/{revisionId}/restore",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/multi-language/set-new-lang-primary": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Set a new primary language",
    "description": "Set a landing page as the primary language of a multi-language group.",
    "operationId": "put-/cms/v3/pages/landing-pages/multi-language/set-new-lang-primary",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}/restore": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Restore a previous version of a Landing Page",
    "description": "Takes a specified version of a Landing Page and restores it.",
    "operationId": "post-/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}/restore",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/draft": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Retrieve the full draft version of the Site Page",
    "description": "Retrieve the full draft version of the Site Page.",
    "operationId": "get-/cms/v3/pages/site-pages/{objectId}/draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Update a Site Page draft",
    "description": "Sparse updates the draft version of a single Site Page object identified by the id in the path.\nYou only need to specify the column values that you are modifying.\n",
    "operationId": "patch-/cms/v3/pages/site-pages/{objectId}/draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/{objectId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieve a Folder",
    "description": "Retrieve the Folder object identified by the id in the path.",
    "operationId": "get-/cms/v3/pages/landing-pages/folders/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Delete a Folder",
    "description": "Delete the Folder object identified by the id in the path.",
    "operationId": "delete-/cms/v3/pages/landing-pages/folders/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update a Folder",
    "description": "Sparse updates a single Folder object identified by the id in the path.\nYou only need to specify the column values that you are modifying.\n",
    "operationId": "patch-/cms/v3/pages/landing-pages/folders/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/batch/read": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Retrieve a batch of Site Pages",
    "description": "Retrieve the Site Page objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/site-pages/batch/read",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/ab-test/create-variation": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Create a new A/B test variation",
    "description": "Create a new A/B test variation based on the information provided in the request body.\n",
    "operationId": "post-/cms/v3/pages/landing-pages/ab-test/create-variation",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Get all Site Pages",
    "description": "Get the list of site pages. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.\n",
    "operationId": "get-/cms/v3/pages/site-pages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Create a new Site Page",
    "description": "Create a new Site Page",
    "operationId": "post-/cms/v3/pages/site-pages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/multi-language/attach-to-lang-group": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Attach a landing page to a multi-language group",
    "description": "Attach a landing page to a multi-language group.",
    "operationId": "post-/cms/v3/pages/landing-pages/multi-language/attach-to-lang-group",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/multi-language/create-language-variation": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Create a new language variation",
    "description": "Create a new language variation from an existing site page",
    "operationId": "post-/cms/v3/pages/site-pages/multi-language/create-language-variation",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieves a previous version of a Landing Page",
    "description": "Retrieves a previous version of a Landing Page",
    "operationId": "get-/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/ab-test/end": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "End an active A/B test",
    "description": "End an active A/B test and designate a winner.",
    "operationId": "post-/cms/v3/pages/landing-pages/ab-test/end",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/draft/push-live": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Push Landing Page draft edits live",
    "description": "Take any changes from the draft version of the Landing Page and apply them to the live version.",
    "operationId": "post-/cms/v3/pages/landing-pages/{objectId}/draft/push-live",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/multi-language/detach-from-lang-group": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Detach a landing page from a multi-language group",
    "description": "Detach a landing page from a multi-language group.",
    "operationId": "post-/cms/v3/pages/landing-pages/multi-language/detach-from-lang-group",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/schedule": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Schedule a Landing Page to be Published",
    "description": "Schedule a Landing Page to be Published",
    "operationId": "post-/cms/v3/pages/landing-pages/schedule",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/ab-test/create-variation": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Create a new A/B test variation",
    "description": "Create a new A/B test variation based on the information provided in the request body.\n",
    "operationId": "post-/cms/v3/pages/site-pages/ab-test/create-variation",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/multi-language/update-languages": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update languages of multi-language group",
    "description": "Explicitly set new languages for each landing page in a multi-language group.",
    "operationId": "post-/cms/v3/pages/landing-pages/multi-language/update-languages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/multi-language/update-languages": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Update languages of multi-language group",
    "description": "Explicitly set new languages for each site page in a multi-language group.",
    "operationId": "post-/cms/v3/pages/site-pages/multi-language/update-languages",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/ab-test/rerun": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Rerun a previous A/B test",
    "description": "Rerun a previous A/B test.",
    "operationId": "post-/cms/v3/pages/landing-pages/ab-test/rerun",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/batch/create": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Create a batch of Site Pages",
    "description": "Create the Site Page objects detailed in the request body.",
    "operationId": "post-/cms/v3/pages/site-pages/batch/create",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/batch/archive": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Delete a batch of Site Pages",
    "description": "Delete the Site Page objects identified in the request body.\nNote: This is not the same as the dashboard `archive` function. To perform a dashboard `archive` send an normal update with the `archivedInDashboard` field set to true.",
    "operationId": "post-/cms/v3/pages/site-pages/batch/archive",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.site_pages.read_write_publish"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/batch/archive": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Delete a batch of Folders",
    "description": "Delete the Folder objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/folders/batch/archive",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/batch/update": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update a batch of Folders",
    "description": "Update the Folder objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/folders/batch/update",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/clone": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Clone a Site Page",
    "description": "Clone a Site Page",
    "operationId": "post-/cms/v3/pages/site-pages/clone",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/multi-language/set-new-lang-primary": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Set a new primary language",
    "description": "Set a site page as the primary language of a multi-language group.",
    "operationId": "put-/cms/v3/pages/site-pages/multi-language/set-new-lang-primary",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/{objectId}/revisions/{revisionId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieves a previous version of a Folder",
    "description": "Retrieves a previous version of a Folder",
    "operationId": "get-/cms/v3/pages/landing-pages/folders/{objectId}/revisions/{revisionId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/draft/reset": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Reset the Landing Page draft to the live version",
    "description": "Discards any edits and resets the draft to the live version.",
    "operationId": "post-/cms/v3/pages/landing-pages/{objectId}/draft/reset",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieve a Landing Page",
    "description": "Retrieve the Landing Page object identified by the id in the path.",
    "operationId": "get-/cms/v3/pages/landing-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Delete a Landing Page",
    "description": "Delete the Landing Page object identified by the id in the path.",
    "operationId": "delete-/cms/v3/pages/landing-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Update a Landing Page",
    "description": "Sparse updates a single Landing Page object identified by the id in the path.\nYou only need to specify the column values that you are modifying.\n",
    "operationId": "patch-/cms/v3/pages/landing-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/multi-language/create-language-variation": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Create a new language variation",
    "description": "Create a new language variation from an existing landing page",
    "operationId": "post-/cms/v3/pages/landing-pages/multi-language/create-language-variation",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/draft/push-live": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Push Site Page draft edits live",
    "description": "Take any changes from the draft version of the Site Page and apply them to the live version.",
    "operationId": "post-/cms/v3/pages/site-pages/{objectId}/draft/push-live",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/batch/archive": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Delete a batch of Landing Pages",
    "description": "Delete the Landing Page objects identified in the request body.\nNote: This is not the same as the dashboard `archive` function. To perform a dashboard `archive` send an normal update with the `archivedInDashboard` field set to true.",
    "operationId": "post-/cms/v3/pages/landing-pages/batch/archive",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/ab-test/rerun": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Rerun a previous A/B test",
    "description": "Rerun a previous A/B test.",
    "operationId": "post-/cms/v3/pages/site-pages/ab-test/rerun",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}/restore-to-draft": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Restore a previous version of a Landing Page, to the draft version of the Landing Page",
    "description": "Takes a specified version of a Landing Page, sets it as the new draft version of the Landing Page.",
    "operationId": "post-/cms/v3/pages/landing-pages/{objectId}/revisions/{revisionId}/restore-to-draft",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}/draft/reset": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Reset the Site Page draft to the live version",
    "description": "Discards any edits and resets the draft to the live version.",
    "operationId": "post-/cms/v3/pages/site-pages/{objectId}/draft/reset",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/site-pages/{objectId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Retrieve a Site Page",
    "description": "Retrieve the Site Page object identified by the id in the path.",
    "operationId": "get-/cms/v3/pages/site-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Delete a Site Page",
    "description": "Delete the Site Page object identified by the id in the path.",
    "operationId": "delete-/cms/v3/pages/site-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write",
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "content",
       "cms.pages.site_pages.read_write_publish"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": {
    "tags": [
     "Site Pages"
    ],
    "summary": "Update a Site Page",
    "description": "Sparse updates a single Site Page object identified by the id in the path.\nYou only need to specify the column values that you are modifying.\n",
    "operationId": "patch-/cms/v3/pages/site-pages/{objectId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.site_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/cms/v3/pages/landing-pages/folders/batch/read": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Landing Pages"
    ],
    "summary": "Retrieve a batch of Folders",
    "description": "Update the Folder objects identified in the request body.",
    "operationId": "post-/cms/v3/pages/landing-pages/folders/batch/read",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "content"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write_publish"
      ]
     },
     {
      "oauth2_legacy": [
       "content"
      ]
     },
     {
      "private_apps_legacy": [
       "cms.pages.landing_pages.read_write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2_legacy": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "content": "Read from and write to my Content",
       "cms.pages.landing_pages.read_write": "Read and write access to Landing Pages",
       "cms.pages.landing_pages.read_write_publish": "Read, write, and publish access to Landing Pages",
       "cms.pages.site_pages.read_write": "Read and write access to Site Pages",
       "cms.pages.site_pages.read_write_publish": "Read, write, and publish access to Site Pages"
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps_legacy": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app-legacy",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   }
  },
  "extensions": {}
 },
 "extensions": null
}