{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations",
    "description" : "Query and interact with existing Conversation threads, messages, and channels",
    "termsOfService" : null,
    "contact" : null,
    "license" : null,
    "version" : "v3",
    "extensions" : null
  },
  "servers" : [ {
    "url" : "https://api.hubapiqa.com",
    "description" : null,
    "variables" : null,
    "extensions" : null
  } ],
  "security" : null,
  "tags" : [ {
    "name" : "Conversations",
    "description" : null,
    "extensions" : null
  } ],
  "paths" : {
    "/conversations/v3/conversations/inboxes" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get conversations inboxes.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/inboxes",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/threads/{threadId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single thread.",
        "description" : "Returns a single thread.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : {
        "tags" : [ "Conversations" ],
        "summary" : "Archives a thread.",
        "description" : "Archives a single thread. The thread will be permanently deleted 30 days after placed in an archived state.",
        "operationId" : "delete-/conversations/v3/conversations/threads/{threadId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : {
        "tags" : [ "Conversations" ],
        "summary" : "Update a thread.",
        "description" : "Updates a single thread. Either a thread's status can be updated, or the thread can be restored.",
        "operationId" : "patch-/conversations/v3/conversations/threads/{threadId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get the original content of a single message.",
        "description" : "Returns the complete original text and rich text bodies of a message. This will be different from the text and rich text in the message itself if the message's `truncationStatus` is anything other than `NOT_TRUNCATED`.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/threads/{threadId}/messages" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get message history for a thread.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : {
        "tags" : [ "Conversations" ],
        "summary" : "Send a message to a thread.",
        "description" : "Send a new message on a thread at the current timestamp.",
        "operationId" : "post-/conversations/v3/conversations/threads/{threadId}/messages",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "conversations.write" ]
        }, {
          "oauth2_legacy" : [ "conversations.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/actors/batch/read" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get actors",
        "description" : "Resolve `ActorId`s to the underlying actors/participants.",
        "operationId" : "post-/conversations/v3/conversations/actors/batch/read",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/channel-accounts" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get channel accounts.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/channel-accounts",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/channels/{channelId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single channel.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/channels/{channelId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single message.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/channels" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get channels.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/channels",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/actors/{actorId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single actor.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/actors/{actorId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/threads" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get threads.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/threads",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/channel-accounts/{channelAccountId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single channel account.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/conversations/v3/conversations/inboxes/{inboxId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Conversations" ],
        "summary" : "Get a single conversations inbox.",
        "description" : null,
        "operationId" : "get-/conversations/v3/conversations/inboxes/{inboxId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2_legacy" : [ "conversations.read" ]
        }, {
          "private_apps_legacy" : [ "conversations.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "OAUTH2",
        "description" : null,
        "name" : null,
        "$ref" : null,
        "in" : null,
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : {
          "implicit" : null,
          "password" : null,
          "clientCredentials" : null,
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "refreshUrl" : null,
            "scopes" : {
              "conversations.read" : "read from conversations",
              "conversations.write" : "write to conversations"
            },
            "extensions" : null
          },
          "extensions" : null
        },
        "openIdConnectUrl" : null,
        "extensions" : null
      },
      "private_apps_legacy" : {
        "type" : "APIKEY",
        "description" : null,
        "name" : "private-app-legacy",
        "$ref" : null,
        "in" : "HEADER",
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : null,
        "openIdConnectUrl" : null,
        "extensions" : null
      }
    },
    "extensions" : { }
  },
  "extensions" : null
}