{
 "openapi": "3.0.1",
 "info": {
  "title": "Users",
  "description": "Add, manage, and remove users from your account",
  "termsOfService": null,
  "contact": null,
  "license": null,
  "version": "v3",
  "extensions": null
 },
 "servers": [
  {
   "url": "https://api.hubapiqa.com",
   "description": null,
   "variables": null,
   "extensions": null
  }
 ],
 "security": null,
 "tags": [
  {
   "name": "Teams",
   "description": null,
   "extensions": null
  },
  {
   "name": "Roles",
   "description": null,
   "extensions": null
  },
  {
   "name": "Users",
   "description": null,
   "extensions": null
  }
 ],
 "paths": {
  "/settings/v3/users/": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Retrieves a list of users from an account",
    "description": "Retrieves a list of users from an account",
    "operationId": "get-/settings/v3/users/",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.read"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Adds a user",
    "description": "New users will only have minimal permissions, which is contacts-base. A welcome email will prompt them to set a password and log in to HubSpot.",
    "operationId": "post-/settings/v3/users/",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.write"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/settings/v3/users/teams": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "See details about this account's teams",
    "description": "View teams for this account",
    "operationId": "get-/settings/v3/users/teams",
    "deprecated": null,
    "security": [
     {
      "oauth2_legacy": [
       "settings.users.teams.read"
      ]
     },
     {
      "private_apps_legacy": [
       "settings.users.teams.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/settings/v3/users/{userId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Retrieves a user",
    "description": "Retrieves a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
    "operationId": "get-/settings/v3/users/{userId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.read"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": {
    "tags": [
     "Users"
    ],
    "summary": "Modifies a user",
    "description": "Modifies a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
    "operationId": "put-/settings/v3/users/{userId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.write"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Removes a user",
    "description": "Removes a user identified by `userId`. `userId` refers to the user's ID by default, or optionally email as specified by the `IdProperty` query param.",
    "operationId": "delete-/settings/v3/users/{userId}",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.write"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/settings/v3/users/roles": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "Retrieves the roles on an account",
    "description": "Retrieves the roles on an account",
    "operationId": "get-/settings/v3/users/roles",
    "deprecated": null,
    "security": [
     {
      "private_apps_legacy": [
       "settings.users.read"
      ]
     },
     {
      "oauth2_legacy": [
       "settings.users.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2_legacy": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "settings.users.write": "Create, modify, and delete users on your account",
       "settings.users.read": "View account data.",
       "settings.users.teams.read": "View teams for this account."
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps_legacy": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app-legacy",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   }
  },
  "extensions": {}
 },
 "extensions": null
}