{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Lists",
    "description" : "CRUD operations to manage lists and list memberships",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapiqa.com"
  } ],
  "tags" : [ {
    "name" : "Memberships"
  } ],
  "paths" : {
    "/crm/v3/lists/{listId}/memberships/add-and-remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add and/or Remove Records from a List",
        "description" : "Add and/or remove records that have already been created in the system to and/or from the list.\nThis endpoint only works with lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-and-remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add All Records from a Source List to a Destination List",
        "description" : "Add all of the records from a source list (specified by the `sourceListId`) to a destination list (specified by the `listId`).\nRecords that are already members of the destination list will be ignored. The destination and source list IDs must be different. The\ndestination and source lists must contain records of the same type (e.g. contacts, companies, etc.).",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Fetch List Memberships Ordered by Record ID",
        "description" : "Fetch list memberships in order sorted by the `recordId` of the records in the list.\nThe `recordId`s are ordered in ascending order if an `after` offset is provided.\nThe `after` parameter will take precedence over `before` if both are provided.",
        "operationId" : "get-/crm/v3/lists/{listId}/memberships",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Delete All Records from a List",
        "description" : "Remove all of the records from a list.\nThis endpoint only works with lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId" : "delete-/crm/v3/lists/{listId}/memberships",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Remove Records from a List",
        "description" : "Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    },
    "/crm/v3/lists/{listId}/memberships/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add Records to a List",
        "description" : "Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.",
        "operationId" : "put-/crm/v3/lists/{listId}/memberships/add",
        "security" : [ {
          "private_apps" : [ "crm.lists.read", "crm.lists.write" ]
        }, {
          "oauth2" : [ "crm.lists.read", "crm.lists.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  }
}