{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Files",
    "description" : "Upload and manage files.",
    "termsOfService" : null,
    "contact" : null,
    "license" : null,
    "version" : "v3",
    "extensions" : null
  },
  "servers" : [ {
    "url" : "https://api.hubapiqa.com",
    "description" : null,
    "variables" : null,
    "extensions" : null
  } ],
  "security" : null,
  "tags" : [ {
    "name" : "Files",
    "description" : null,
    "extensions" : null
  }, {
    "name" : "Folders",
    "description" : null,
    "extensions" : null
  } ],
  "paths" : {
    "/files/v3/files/{fileId}/gdpr-delete" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : null,
      "delete" : {
        "tags" : [ "Files" ],
        "summary" : "GDPR delete",
        "description" : "GDRP delete file",
        "operationId" : "delete-/files/v3/files/{fileId}/gdpr-delete",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders/{folderId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Get folder",
        "description" : "Get folder by ID",
        "operationId" : "get-/files/v3/folders/{folderId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Delete folder.",
        "description" : "Delete folder by ID.",
        "operationId" : "delete-/files/v3/folders/{folderId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/{fileId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Get file.",
        "description" : "Get file by ID.",
        "operationId" : "get-/files/v3/files/{fileId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : {
        "tags" : [ "Files" ],
        "summary" : "Replace file.",
        "description" : "Replace existing file data with new file data. Can be used to change image content without having to upload a new file and update all references.",
        "operationId" : "put-/files/v3/files/{fileId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "post" : null,
      "delete" : {
        "tags" : [ "Files" ],
        "summary" : "Delete file",
        "description" : "Delete file by ID",
        "operationId" : "delete-/files/v3/files/{fileId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : {
        "tags" : [ "Files" ],
        "summary" : "update file properties",
        "description" : "Update properties of file by ID.",
        "operationId" : "patch-/files/v3/files/{fileId}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Files" ],
        "summary" : "Upload file",
        "description" : "Upload a single file with content specified in request body.",
        "operationId" : "post-/files/v3/files",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Create folder.",
        "description" : "Creates a folder.",
        "operationId" : "post-/files/v3/folders",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/{fileId}/signed-url" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Get signed URL to access private file.",
        "description" : "Generates signed URL that allows temporary access to a private file.",
        "operationId" : "get-/files/v3/files/{fileId}/signed-url",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/stat/{path}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Files" ],
        "summary" : null,
        "description" : null,
        "operationId" : "get-/files/v3/files/stat/{path}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/import-from-url/async" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Files" ],
        "summary" : "Import a file from a URL into the file manager.",
        "description" : "Asynchronously imports the file at the given URL into the file manager.",
        "operationId" : "post-/files/v3/files/import-from-url/async",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders/search" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Search folders",
        "description" : "Search for folders. Does not contain hidden or archived folders.",
        "operationId" : "get-/files/v3/folders/search",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders/update/async/tasks/{taskId}/status" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Check folder update status.",
        "description" : "Check status of folder update. Folder updates happen asynchronously.",
        "operationId" : "get-/files/v3/folders/update/async/tasks/{taskId}/status",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/search" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Search files",
        "description" : "Search through files in the file manager. Does not display hidden or archived files.",
        "operationId" : "get-/files/v3/files/search",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders/{folderPath}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Folders" ],
        "summary" : "Get folder.",
        "description" : "Get folder by path.",
        "operationId" : "get-/files/v3/folders/{folderPath}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : {
        "tags" : [ "Folders" ],
        "summary" : "Delete folder.",
        "description" : "Delete folder by path.",
        "operationId" : "delete-/files/v3/folders/{folderPath}",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/folders/update/async" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Folders" ],
        "summary" : "Update folder properties",
        "description" : "Update properties of folder by given ID. This action happens asynchronously and will update all of the folder's children as well.",
        "operationId" : "post-/files/v3/folders/update/async",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files.write" ]
        }, {
          "private_apps_legacy" : [ "files.write" ]
        }, {
          "oauth2_legacy" : [ "filemanager.write" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.write" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/files/v3/files/import-from-url/async/tasks/{taskId}/status" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Files" ],
        "summary" : "Check import status.",
        "description" : "Check the status of requested import.",
        "operationId" : "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status",
        "deprecated" : null,
        "security" : [ {
          "private_apps_legacy" : [ "files.read" ]
        }, {
          "private_apps_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "oauth2_legacy" : [ "files.ui_hidden.read" ]
        }, {
          "private_apps_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files" ]
        }, {
          "oauth2_legacy" : [ "files.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "OAUTH2",
        "description" : null,
        "name" : null,
        "$ref" : null,
        "in" : null,
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : {
          "implicit" : null,
          "password" : null,
          "clientCredentials" : null,
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "refreshUrl" : null,
            "scopes" : {
              "files" : "Read from and write to my Files",
              "files.read" : "View files",
              "files.ui_hidden.read" : "View hidden files",
              "files.write" : "Make changes to files",
              "filemanager.write" : "Create, modify, and delete files and folders in the file manager",
              "files.ui_hidden.write" : "Make changes to hidden files"
            },
            "extensions" : null
          },
          "extensions" : null
        },
        "openIdConnectUrl" : null,
        "extensions" : null
      },
      "private_apps_legacy" : {
        "type" : "APIKEY",
        "description" : null,
        "name" : "private-app-legacy",
        "$ref" : null,
        "in" : "HEADER",
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : null,
        "openIdConnectUrl" : null,
        "extensions" : null
      }
    },
    "extensions" : { }
  },
  "extensions" : null
}