{
 "openapi": "3.0.1",
 "info": {
  "title": "List App",
  "description": "List definition CRUD operations and memberships discovery and management",
  "termsOfService": null,
  "contact": null,
  "license": null,
  "version": "v3",
  "extensions": null
 },
 "servers": [
  {
   "url": "https://api.hubapiqa.com",
   "description": null,
   "variables": null,
   "extensions": null
  }
 ],
 "security": null,
 "tags": [
  {
   "name": "Memberships",
   "description": null,
   "extensions": null
  },
  {
   "name": "Lists",
   "description": null,
   "extensions": null
  }
 ],
 "paths": {
  "/list-app/v3/list-memberships/{listId}/add": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Memberships"
    ],
    "summary": "Adds records with ids provided to the list",
    "description": "Add members to the list",
    "operationId": "put-/list-app/v3/list-memberships/{listId}/add",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/list-memberships/{listId}/add-from/{sourceListId}": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Memberships"
    ],
    "summary": "Adds to target list all the members from source list",
    "description": "Add to list all the members of source list",
    "operationId": "put-/list-app/v3/list-memberships/{listId}/add-from/{sourceListId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/{listId}/restore": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Lists"
    ],
    "summary": "Restore the recently deleted list. Only lists deleted within 90 days can be restored",
    "description": "Restore list definition",
    "operationId": "put-/list-app/v3/lists/{listId}/restore",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/search": {
   "summary": null,
   "description": null,
   "get": null,
   "put": null,
   "post": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "post-/list-app/v3/lists/search",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/{listId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "get-/list-app/v3/lists/{listId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": {
    "tags": [
     "Lists"
    ],
    "summary": "Deletes the list definition with possibility to restore it for up to 90 days after deletion",
    "description": "Remove list definition",
    "operationId": "delete-/list-app/v3/lists/{listId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/list-memberships/{listId}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Memberships"
    ],
    "summary": "Returns ids of records that are members of the list ordered by recordId",
    "description": "Get memberships (recordId order)",
    "operationId": "get-/list-app/v3/list-memberships/{listId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": {
    "tags": [
     "Memberships"
    ],
    "summary": "Add and/or remove records that have already been created in the system to/from list within the same API call.",
    "description": "Edit list memberships",
    "operationId": "put-/list-app/v3/list-memberships/{listId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": {
    "tags": [
     "Memberships"
    ],
    "summary": "Removes all the members from the list",
    "description": "Delete all members from list",
    "operationId": "delete-/list-app/v3/list-memberships/{listId}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "get-/list-app/v3/lists",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "post-/list-app/v3/lists",
    "deprecated": null,
    "security": [
     {
      "oauth2": [
       "crm.lists.write"
      ]
     },
     {
      "private_apps": [
       "crm.lists.write"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/list-memberships/{listId}/remove": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Memberships"
    ],
    "summary": "Removes records with ids provided from the list",
    "description": "Remove records from the list",
    "operationId": "put-/list-app/v3/list-memberships/{listId}/remove",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/{listId}/update-list-filters": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "put-/list-app/v3/lists/{listId}/update-list-filters",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/{listId}/update-list-name": {
   "summary": null,
   "description": null,
   "get": null,
   "put": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "put-/list-app/v3/lists/{listId}/update-list-name",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.write",
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  },
  "/list-app/v3/lists/object-type-id/{objectTypeId}/name/{listName}": {
   "summary": null,
   "description": null,
   "get": {
    "tags": [
     "Lists"
    ],
    "summary": null,
    "description": null,
    "operationId": "get-/list-app/v3/lists/object-type-id/{objectTypeId}/name/{listName}",
    "deprecated": null,
    "security": [
     {
      "private_apps": [
       "crm.lists.read"
      ]
     },
     {
      "oauth2": [
       "crm.lists.read"
      ]
     }
    ],
    "servers": null,
    "extensions": null
   },
   "put": null,
   "post": null,
   "delete": null,
   "options": null,
   "head": null,
   "patch": null,
   "trace": null,
   "servers": null,
   "$ref": null,
   "extensions": null
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2": {
    "type": "OAUTH2",
    "description": null,
    "name": null,
    "$ref": null,
    "in": null,
    "scheme": null,
    "bearerFormat": null,
    "flows": {
     "implicit": null,
     "password": null,
     "clientCredentials": null,
     "authorizationCode": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "refreshUrl": null,
      "scopes": {
       "crm.lists.read": " ",
       "crm.lists.write": " "
      },
      "extensions": null
     },
     "extensions": null
    },
    "openIdConnectUrl": null,
    "extensions": null
   },
   "private_apps": {
    "type": "APIKEY",
    "description": null,
    "name": "private-app",
    "$ref": null,
    "in": "HEADER",
    "scheme": null,
    "bearerFormat": null,
    "flows": null,
    "openIdConnectUrl": null,
    "extensions": null
   }
  },
  "extensions": {}
 },
 "extensions": null
}