{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "List App",
    "description" : "List definition CRUD operations and memberships discovery and management",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapiqa.com"
  } ],
  "tags" : [ {
    "name" : "Memberships"
  }, {
    "name" : "Lists"
  } ],
  "paths" : {
    "/list-app/v3/list-memberships/{listId}/add" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Adds records with ids provided to the list",
        "description" : "Add members to the list",
        "operationId" : "put-/list-app/v3/list-memberships/{listId}/add",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/list-memberships/{listId}/add-from/{sourceListId}" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Adds to target list all the members from source list",
        "description" : "Add to list all the members of source list",
        "operationId" : "put-/list-app/v3/list-memberships/{listId}/add-from/{sourceListId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/{listId}/restore" : {
      "put" : {
        "tags" : [ "Lists" ],
        "summary" : "Restore the recently deleted list. Only lists deleted within 90 days can be restored",
        "description" : "Restore list definition",
        "operationId" : "put-/list-app/v3/lists/{listId}/restore",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/search" : {
      "post" : {
        "tags" : [ "Lists" ],
        "operationId" : "post-/list-app/v3/lists/search",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/{listId}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "operationId" : "get-/list-app/v3/lists/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Lists" ],
        "summary" : "Deletes the list definition with possibility to restore it for up to 90 days after deletion",
        "description" : "Remove list definition",
        "operationId" : "delete-/list-app/v3/lists/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/list-memberships/{listId}" : {
      "get" : {
        "tags" : [ "Memberships" ],
        "summary" : "Returns ids of records that are members of the list ordered by recordId",
        "description" : "Get memberships (recordId order)",
        "operationId" : "get-/list-app/v3/list-memberships/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Add and/or remove records that have already been created in the system to/from list within the same API call.",
        "description" : "Edit list memberships",
        "operationId" : "put-/list-app/v3/list-memberships/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Memberships" ],
        "summary" : "Removes all the members from the list",
        "description" : "Delete all members from list",
        "operationId" : "delete-/list-app/v3/list-memberships/{listId}",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists" : {
      "get" : {
        "tags" : [ "Lists" ],
        "operationId" : "get-/list-app/v3/lists",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Lists" ],
        "operationId" : "post-/list-app/v3/lists",
        "security" : [ {
          "oauth2" : [ "crm.lists.write" ]
        }, {
          "private_apps" : [ "crm.lists.write" ]
        } ]
      }
    },
    "/list-app/v3/list-memberships/{listId}/remove" : {
      "put" : {
        "tags" : [ "Memberships" ],
        "summary" : "Removes records with ids provided from the list",
        "description" : "Remove records from the list",
        "operationId" : "put-/list-app/v3/list-memberships/{listId}/remove",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/{listId}/update-list-filters" : {
      "put" : {
        "tags" : [ "Lists" ],
        "operationId" : "put-/list-app/v3/lists/{listId}/update-list-filters",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/{listId}/update-list-name" : {
      "put" : {
        "tags" : [ "Lists" ],
        "operationId" : "put-/list-app/v3/lists/{listId}/update-list-name",
        "security" : [ {
          "private_apps" : [ "crm.lists.write", "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.write", "crm.lists.read" ]
        } ]
      }
    },
    "/list-app/v3/lists/object-type-id/{objectTypeId}/name/{listName}" : {
      "get" : {
        "tags" : [ "Lists" ],
        "operationId" : "get-/list-app/v3/lists/object-type-id/{objectTypeId}/name/{listName}",
        "security" : [ {
          "private_apps" : [ "crm.lists.read" ]
        }, {
          "oauth2" : [ "crm.lists.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "OAUTH2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.lists.read" : " ",
              "crm.lists.write" : " "
            }
          }
        }
      },
      "private_apps" : {
        "type" : "APIKEY",
        "name" : "private-app",
        "in" : "HEADER"
      }
    },
    "extensions" : { }
  }
}