{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Quotes",
    "description" : "",
    "termsOfService" : null,
    "contact" : null,
    "license" : null,
    "version" : "v3",
    "extensions" : null
  },
  "servers" : [ {
    "url" : "https://api.hubapiqa.com",
    "description" : null,
    "variables" : null,
    "extensions" : null
  } ],
  "security" : null,
  "tags" : [ {
    "name" : "Batch",
    "description" : null,
    "extensions" : null
  }, {
    "name" : "Basic",
    "description" : null,
    "extensions" : null
  }, {
    "name" : "Public_Object",
    "description" : null,
    "extensions" : null
  }, {
    "name" : "GDPR",
    "description" : null,
    "extensions" : null
  }, {
    "name" : "Search",
    "description" : null,
    "extensions" : null
  } ],
  "paths" : {
    "/crm/v3/objects/quotes/batch/archive" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of quotes by ID",
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/batch/archive",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of quotes. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/quotes",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a quote with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard quotes is provided.",
        "operationId" : "post-/crm/v3/objects/quotes",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/{quoteId}" : {
      "summary" : null,
      "description" : null,
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{quoteId}`. `{quoteId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/quotes/{quoteId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "put" : null,
      "post" : null,
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{quoteId}` to the recycling bin.",
        "operationId" : "delete-/crm/v3/objects/quotes/{quoteId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "options" : null,
      "head" : null,
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{quoteId}`. `{quoteId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/quotes/{quoteId}",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/batch/update" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of quotes",
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/batch/update",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/batch/create" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of quotes",
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/batch/create",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/merge" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Public_Object" ],
        "summary" : "Merge two quotes with same type",
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/merge",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/search" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Search" ],
        "summary" : null,
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/search",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ],
        "servers" : null,
        "extensions" : {
          "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
        }
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/batch/read" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of quotes by internal ID, or unique property values",
        "description" : null,
        "operationId" : "post-/crm/v3/objects/quotes/batch/read",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.read" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.read" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    },
    "/crm/v3/objects/quotes/gdpr-delete" : {
      "summary" : null,
      "description" : null,
      "get" : null,
      "put" : null,
      "post" : {
        "tags" : [ "GDPR" ],
        "summary" : "GDPR DELETE",
        "description" : "Permanently delete a contact and all associated content to follow GDPR. Use optional property 'idProperty' set to 'email' to identify contact by email address. If email address is not found, the email address will be added to a blocklist and prevent it from being used in the future.",
        "operationId" : "post-/crm/v3/objects/quotes/gdpr-delete",
        "deprecated" : null,
        "security" : [ {
          "oauth2" : [ "crm.objects.quotes.write" ]
        }, {
          "private_apps" : [ "crm.objects.quotes.write" ]
        } ],
        "servers" : null,
        "extensions" : null
      },
      "delete" : null,
      "options" : null,
      "head" : null,
      "patch" : null,
      "trace" : null,
      "servers" : null,
      "$ref" : null,
      "extensions" : null
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "OAUTH2",
        "description" : null,
        "name" : null,
        "$ref" : null,
        "in" : null,
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : {
          "implicit" : null,
          "password" : null,
          "clientCredentials" : null,
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "refreshUrl" : null,
            "scopes" : {
              "crm.objects.goals.write" : "Write goals",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records",
              "crm.objects.custom.read" : "View custom object records",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets"
            },
            "extensions" : null
          },
          "extensions" : null
        },
        "openIdConnectUrl" : null,
        "extensions" : null
      },
      "oauth2" : {
        "type" : "OAUTH2",
        "description" : null,
        "name" : null,
        "$ref" : null,
        "in" : null,
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : {
          "implicit" : null,
          "password" : null,
          "clientCredentials" : null,
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "refreshUrl" : null,
            "scopes" : {
              "crm.objects.deals.write" : " ",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.read" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.objects.contacts.read" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.deals.read" : " ",
              "crm.objects.line_items.read" : "Line Items"
            },
            "extensions" : null
          },
          "extensions" : null
        },
        "openIdConnectUrl" : null,
        "extensions" : null
      },
      "private_apps_legacy" : {
        "type" : "APIKEY",
        "description" : null,
        "name" : "private-app-legacy",
        "$ref" : null,
        "in" : "HEADER",
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : null,
        "openIdConnectUrl" : null,
        "extensions" : null
      },
      "private_apps" : {
        "type" : "APIKEY",
        "description" : null,
        "name" : "private-app",
        "$ref" : null,
        "in" : "HEADER",
        "scheme" : null,
        "bearerFormat" : null,
        "flows" : null,
        "openIdConnectUrl" : null,
        "extensions" : null
      }
    },
    "extensions" : { }
  },
  "extensions" : null
}